version: "3.3"

services:
  postgres:
    image: postgres:11.0
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
    volumes:
      - ./pgdata:/var/lib/postgresql/data
