version: "3.3"

services:
  cassandra:
    image: cassandra:3.11
    ports:
      - 7000:7000
      - 9042:9042
    # environment:
    #   - CASSANDRA_SEEDS=127.0.0.1
    volumes:
      - ./cassandra_data:/var/lib/cassandra
